/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McsRouteImport } from './routes/mcs'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as BatalhasRouteImport } from './routes/batalhas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McsIndexRouteImport } from './routes/mcs.index'
import { Route as BatalhasIndexRouteImport } from './routes/batalhas.index'
import { Route as McsIdRouteImport } from './routes/mcs.$id'
import { Route as BatalhasIdRouteImport } from './routes/batalhas.$id'

const McsRoute = McsRouteImport.update({
  id: '/mcs',
  path: '/mcs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const BatalhasRoute = BatalhasRouteImport.update({
  id: '/batalhas',
  path: '/batalhas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McsIndexRoute = McsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => McsRoute,
} as any)
const BatalhasIndexRoute = BatalhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BatalhasRoute,
} as any)
const McsIdRoute = McsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => McsRoute,
} as any)
const BatalhasIdRoute = BatalhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BatalhasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batalhas': typeof BatalhasRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/mcs': typeof McsRouteWithChildren
  '/batalhas/': typeof BatalhasIndexRoute
  '/mcs/': typeof McsIndexRoute
  '/batalhas/$id': typeof BatalhasIdRoute
  '/mcs/$id': typeof McsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/batalhas': typeof BatalhasIndexRoute
  '/mcs': typeof McsIndexRoute
  '/batalhas/$id': typeof BatalhasIdRoute
  '/mcs/$id': typeof McsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batalhas': typeof BatalhasRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/mcs': typeof McsRouteWithChildren
  '/batalhas/': typeof BatalhasIndexRoute
  '/mcs/': typeof McsIndexRoute
  '/batalhas/$id': typeof BatalhasIdRoute
  '/mcs/$id': typeof McsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batalhas'
    | '/historico'
    | '/mcs'
    | '/batalhas/'
    | '/mcs/'
    | '/batalhas/$id'
    | '/mcs/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historico' | '/batalhas' | '/mcs' | '/batalhas/$id' | '/mcs/$id'
  id:
    | '__root__'
    | '/'
    | '/batalhas'
    | '/historico'
    | '/mcs'
    | '/batalhas/'
    | '/mcs/'
    | '/batalhas/$id'
    | '/mcs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatalhasRoute: typeof BatalhasRouteWithChildren
  HistoricoRoute: typeof HistoricoRoute
  McsRoute: typeof McsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcs': {
      id: '/mcs'
      path: '/mcs'
      fullPath: '/mcs'
      preLoaderRoute: typeof McsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batalhas': {
      id: '/batalhas'
      path: '/batalhas'
      fullPath: '/batalhas'
      preLoaderRoute: typeof BatalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcs/': {
      id: '/mcs/'
      path: '/'
      fullPath: '/mcs/'
      preLoaderRoute: typeof McsIndexRouteImport
      parentRoute: typeof McsRoute
    }
    '/batalhas/': {
      id: '/batalhas/'
      path: '/'
      fullPath: '/batalhas/'
      preLoaderRoute: typeof BatalhasIndexRouteImport
      parentRoute: typeof BatalhasRoute
    }
    '/mcs/$id': {
      id: '/mcs/$id'
      path: '/$id'
      fullPath: '/mcs/$id'
      preLoaderRoute: typeof McsIdRouteImport
      parentRoute: typeof McsRoute
    }
    '/batalhas/$id': {
      id: '/batalhas/$id'
      path: '/$id'
      fullPath: '/batalhas/$id'
      preLoaderRoute: typeof BatalhasIdRouteImport
      parentRoute: typeof BatalhasRoute
    }
  }
}

interface BatalhasRouteChildren {
  BatalhasIndexRoute: typeof BatalhasIndexRoute
  BatalhasIdRoute: typeof BatalhasIdRoute
}

const BatalhasRouteChildren: BatalhasRouteChildren = {
  BatalhasIndexRoute: BatalhasIndexRoute,
  BatalhasIdRoute: BatalhasIdRoute,
}

const BatalhasRouteWithChildren = BatalhasRoute._addFileChildren(
  BatalhasRouteChildren,
)

interface McsRouteChildren {
  McsIndexRoute: typeof McsIndexRoute
  McsIdRoute: typeof McsIdRoute
}

const McsRouteChildren: McsRouteChildren = {
  McsIndexRoute: McsIndexRoute,
  McsIdRoute: McsIdRoute,
}

const McsRouteWithChildren = McsRoute._addFileChildren(McsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatalhasRoute: BatalhasRouteWithChildren,
  HistoricoRoute: HistoricoRoute,
  McsRoute: McsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()